'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class English
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FlashcatUSB.English", GetType(English).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Board firmware version.
        '''</summary>
        Friend Shared ReadOnly Property cnts_avrver() As String
            Get
                Return ResourceManager.GetString("cnts_avrver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connected to device.
        '''</summary>
        Friend Shared ReadOnly Property cnts_device() As String
            Get
                Return ResourceManager.GetString("cnts_device", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash memory name.
        '''</summary>
        Friend Shared ReadOnly Property cnts_flashname() As String
            Get
                Return ResourceManager.GetString("cnts_flashname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash memory size.
        '''</summary>
        Friend Shared ReadOnly Property cnts_flashsize() As String
            Get
                Return ResourceManager.GetString("cnts_flashsize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash memory type.
        '''</summary>
        Friend Shared ReadOnly Property cnts_flashtype() As String
            Get
                Return ResourceManager.GetString("cnts_flashtype", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Device mode.
        '''</summary>
        Friend Shared ReadOnly Property cnts_mode() As String
            Get
                Return ResourceManager.GetString("cnts_mode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Active script.
        '''</summary>
        Friend Shared ReadOnly Property cnts_script() As String
            Get
                Return ResourceManager.GetString("cnts_script", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: The hex file data is larger than the size of the DFU memory.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erasing the AVR flash memory.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sending AVR DFU erase command.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_err3() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_err3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: AVR flash erase failed.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_err4() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_err4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: AVR flash write failed.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_err5() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_err5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AVR DFU command successful.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_sucess() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_sucess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AVR flash written successfully.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_writedone() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_writedone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New AVR firmware programmed (click &apos;Start Appplication&apos; to begin).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_writedonegui() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_writedonegui", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Beginning AVR flash write ({0} bytes).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avrwrite() As String
            Get
                Return ResourceManager.GetString("fcusb_avrwrite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Base address.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_baseaddress() As String
            Get
                Return ResourceManager.GetString("fcusb_baseaddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cancel() As String
            Get
                Return ResourceManager.GetString("fcusb_cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash base address: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_base() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_base", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ({0} bit bus).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_bitbus() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_bitbus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash description: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_desc() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CFI erase operation complete!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_erasecomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_erasecomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erasing CFI flash (this could take a moment).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_erasing() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_erasing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to open device in JEDEC mode.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loaded CFI compatible flash device at: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_founddev() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_founddev", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Changing parameter for existing part: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_info1() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_info1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to interface.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_interface() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_interface", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash JEDEC ID: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_jedecid() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_jedecid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Programming mode.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_pmode() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_pmode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Unknown).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_unknown() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_unknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose AVR firmware to program.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_common_avrtoprog() As String
            Get
                Return ResourceManager.GetString("fcusb_common_avrtoprog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose location to save the console log.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_console_save() As String
            Get
                Return ResourceManager.GetString("fcusb_console_save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Device connected in DFU bootloader mode.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_conn() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_conn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File: no file currently loaded.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_file_default() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_file_default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load File.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_loadfile() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_loadfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Program.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_progfile() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_progfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB ready for operation in DFU mode.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_ready() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start application.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_startprog() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_startprog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Disconnected from FlashcatUSB.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_disconnected() As String
            Get
                Return ResourceManager.GetString("fcusb_disconnected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: failed to retrieve board firmware version.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please upgrade AVR firmware to {0} or newer.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB board has outdated firmware.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err3() As String
            Get
                Return ResourceManager.GetString("fcusb_err3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB failed to connect to target board using JTAG.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err4() As String
            Get
                Return ResourceManager.GetString("fcusb_err4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to set value (invalid input).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err5() As String
            Get
                Return ResourceManager.GetString("fcusb_err5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to set value (value is larger than one byte).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err6() As String
            Get
                Return ResourceManager.GetString("fcusb_err6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to set value (value is larger than four bytes).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err7() As String
            Get
                Return ResourceManager.GetString("fcusb_err7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: file is corrupt or not a AVR Hex file.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err8() As String
            Get
                Return ResourceManager.GetString("fcusb_err8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_file() As String
            Get
                Return ResourceManager.GetString("fcusb_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User canceled. No data has been saved.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_filesave_canceled() As String
            Get
                Return ResourceManager.GetString("fcusb_filesave_canceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} successfully saved to disk.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_filesave_sucess() As String
            Get
                Return ResourceManager.GetString("fcusb_filesave_sucess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Converted data read into Intel hex format for saving.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_filesave_tohex() As String
            Get
                Return ResourceManager.GetString("fcusb_filesave_tohex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose hard drive location and output data format.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_filesave_type() As String
            Get
                Return ResourceManager.GetString("fcusb_filesave_type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to write data to flash device (out of bounds).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_flasherr1() As String
            Get
                Return ResourceManager.GetString("fcusb_flasherr1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File: no file currently loaded.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_hex_nofile() As String
            Get
                Return ResourceManager.GetString("fcusb_hex_nofile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Initializing EJTAG engine.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_initjtag() As String
            Get
                Return ResourceManager.GetString("fcusb_initjtag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Device connected in JTAG mode: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_conn() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_conn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: sent processor reset command.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_cpureset() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_cpureset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: Processor entered into debug mode.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_debugon() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_debugon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Target device supports DMA mode.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_dma() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_dma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erase operation complete!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_erasecomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_erasecomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error connecting to target board.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Failed to connect to EJTAG device.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash device found at: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_foundat() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_foundat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CFI: Found compatible flash device at: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_foundcfi() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_foundcfi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: IR length set to {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_irlen() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_irlen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Target device does not support DMA mode.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_nodma() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_nodma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash device could not be found.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_notfound() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_notfound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: Device only supports non-dma (PrAcc) mode and non-pracc firmware is loaded into FlashcatUSB.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_praccmode() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_praccmode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB ready for operation in JTAG mode.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_ready() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Searching for CFI compliant Flash device.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_searchcfi() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_searchcfi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Searching for a CFI Flash @ {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_searchcfiat() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_searchcfiat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: SPI flash detected ({0}).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_spidetected() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_spidetected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erasing entire SPI flash (this could take a moment).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_spierasing() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_spierasing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: SPI register returned {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_spiregret() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_spiregret", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG engine setup successfully.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtagsetup() As String
            Get
                Return ResourceManager.GetString("fcusb_jtagsetup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Length.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_length() As String
            Get
                Return ResourceManager.GetString("fcusb_length", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LibUsbDotNet version: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_libusb_ver() As String
            Get
                Return ResourceManager.GetString("fcusb_libusb_ver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_address() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_address", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User cancelled write operation.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_cancelled() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_cancelled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose file to write into {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_choosefile() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_choosefile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error, file does not exist or contains no data.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error while trying to read data.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File chosen, writting into {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_filechosen() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_filechosen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opened file for writing: {0} (binary hex format), total file size: {1} bytes.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_opened_bin() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_opened_bin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opened file for writing: {0} (Intel hex format), total file size: {1} bytes.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_opened_intel() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_opened_intel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Read operation canceled.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_readcanceled() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_readcanceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Read complete, please choose location and format type.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_readcomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_readcomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select range to read from {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_readfrom() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_readfrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Beginning memory read operation.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_readstart() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_readstart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select range to write data to {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_selectwriterange() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_selectwriterange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User cancelled read operation.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_usercanceledread() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_usercanceledread", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User canceled. No data written to {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_usercanwrite() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_usercanwrite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash write operation canceled.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_writecanceled() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_writecanceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Write operation complete: {0} bytes written..
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_writecomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_writecomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Beginning memory write operation.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_writestart() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_writestart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Writing file {0} into {1} ({2} bytes to write).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_writing() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_writing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Memory Device.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memdev() As String
            Get
                Return ResourceManager.GetString("fcusb_memdev", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Beginning memory read from {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_beginread() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_beginread", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bulk erase not supported for DRAM devices.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_dram_notsup() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_dram_notsup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MemoryInit: Failed - device parameters failed Init.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Can not detect SPI flash (API not loaded for current MCU).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MemoryInit: Failed - Unable to connect to PrAcc memory interface (AVR firmware does not support).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_nopraccsupport() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_nopraccsupport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Read operation complete.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_readdone() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_readdone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start address: {0} ({1}) Length: {2}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_startaddr() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_startaddr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verifing written data at {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_verify() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_verify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: Flash verify read an incorrect number of bytes.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_verifyerr1() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_verifyerr1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address {0}: wrote {1} and read {2} ({3} mismatches).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_verifyerr2() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_verifyerr2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: data verification at {0} failed!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_verifyfailed() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_verifyfailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data verification was successful.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_verifyokay() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_verifyokay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to write data (device is read-only).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_write_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_write_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Writing address {0} with {1} bytes ({2}).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_writeaddr() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_writeaddr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Write Flash operation complete!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_writecomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_writecomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Write operation complete, {0} bytes written..
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_writedone() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_writedone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} bytes written in {1} seconds, {2} Bytes/s.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_writespeed() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_writespeed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AVR Firmware.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_avrfw() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_avrfw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Console.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_console() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_console", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current script.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_cscript() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_cscript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detect device.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_detectdevice() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_detectdevice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_exit() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_exit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Language.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_language() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_language", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Load script.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_loadscript() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_loadscript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Main.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_main() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_main", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Script.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_script() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_script", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Settings.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_settings() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use automatic settings.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_auto() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_auto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bit Order.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_bitorder() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_bitorder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chip Erase.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_chiperase() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_chiperase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chip Size.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_chipsize() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_chipsize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clock Divider.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_clodiv() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_clodiv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI device commands.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_devcmds() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_devcmds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enable Write Status.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_enwrstatus() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_enwrstatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erase Size.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_erasesize() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_erasesize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use the values commonly found in the device&apos;s datasheet.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_info() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Program Mode.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_pmode() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_pmode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Page Program.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_pp() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_pp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Read.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_read() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_read", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Read Status.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_rstatus() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_rstatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sector Erase.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_serase() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_serase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI Mode.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_spimode() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_spimode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use these settings.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_usesettings() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_usesettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use &apos;Enable Write Status&apos;.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_usewren() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_usewren", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Write Enable.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_we() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_we", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Write Status.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_wstatus() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_wstatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI Settings.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spisettings() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spisettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_status() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unload script.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_unloadscript() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_unloadscript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verify programming.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_verify() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_verify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Device connected in NAND over SPI mode.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nand_conn() As String
            Get
                Return ResourceManager.GetString("fcusb_nand_conn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB ready for operation in NAND mode.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nand_ready() As String
            Get
                Return ResourceManager.GetString("fcusb_nand_ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Programming new AVR firmware.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_newavrfw() As String
            Get
                Return ResourceManager.GetString("fcusb_newavrfw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (no flash detected).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_noflash() As String
            Get
                Return ResourceManager.GetString("fcusb_noflash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data successfully read and parsed.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_dataread() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_dataread", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: No CFG area Found!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error loading Non-Vol data.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Not found).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_notfound() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_notfound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reading Non-Vol configuration data.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_readingnonvol() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_readingnonvol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Writing Non-Vol configuration to Flash.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_writing() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_writing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Done. Non-Vol config updated.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_wrote() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_wrote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_okbutton() As String
            Get
                Return ResourceManager.GetString("fcusb_okbutton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Range:.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_range() As String
            Get
                Return ResourceManager.GetString("fcusb_range", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Read.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_Read() As String
            Get
                Return ResourceManager.GetString("fcusb_Read", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Running on: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_running() As String
            Get
                Return ResourceManager.GetString("fcusb_running", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking for a device specific script to automatically load.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_check() As String
            Get
                Return ResourceManager.GetString("fcusb_script_check", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loaded script {0} successfully.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_loaded() As String
            Get
                Return ResourceManager.GetString("fcusb_script_loaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading device specific script: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_loading() As String
            Get
                Return ResourceManager.GetString("fcusb_script_loading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No script files available.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_none() As String
            Get
                Return ResourceManager.GetString("fcusb_script_none", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Can not load script (file does not exist).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_notexist() As String
            Get
                Return ResourceManager.GetString("fcusb_script_notexist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select FlashcatUSB script file to open.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_open() As String
            Get
                Return ResourceManager.GetString("fcusb_script_open", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The script {0} has been unloaded.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_unload() As String
            Get
                Return ResourceManager.GetString("fcusb_script_unload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connected to Flash.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_connflash() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_connflash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to For read write support email contact@embeddedcomputers.net with JEDEC ID.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_email() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash erase complete in {0} seconds.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_erasecomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_erasecomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erasing entire flash device, total size: {0} bytes (this may take a moment).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_erasingbulk() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_erasingbulk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB connected in SPI mode but no Flash detected.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB detected SPI device but its not currently supported.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI device size must be at least one megabit.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_err3() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_err3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI device size must be a multiple of a megabit.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_err4() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_err4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to connect to compatible SPI device.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_err5() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_err5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash detected: {0} ({1} bytes).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_flashdetected() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_flashdetected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error setting SPI mode, mode not supported: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_modenotsupported() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_modenotsupported", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI mode set to auto configure.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_modesetauto() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_modesetauto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI mode set to {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_modesetto() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_modesetto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opening device in SPI Mode.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_openinmode() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_openinmode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Programming mode: SPI (high-speed).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_progmode() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_progmode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB ready for operation in SPI mode.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_ready() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scanning for spi flash.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_scanning() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_scanning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Using custom settings from SPI Settings page.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_usingcustom() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_usingcustom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Device connected in SPI mode, firmware version: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_ver() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_ver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB status: Connected.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_status_connected() As String
            Get
                Return ResourceManager.GetString("fcusb_status_connected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB status: Disconnected.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_status_disconnect() As String
            Get
                Return ResourceManager.GetString("fcusb_status_disconnect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to STOP.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_stop() As String
            Get
                Return ResourceManager.GetString("fcusb_stop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Software waiting for device to be connected via USB.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_waitingforusb() As String
            Get
                Return ResourceManager.GetString("fcusb_waitingforusb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Welcome to FlashcatUSB interfacing software, build: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_welcome() As String
            Get
                Return ResourceManager.GetString("fcusb_welcome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Welcome to FlashcatUSB!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_welcome_status() As String
            Get
                Return ResourceManager.GetString("fcusb_welcome_status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Write.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_Write() As String
            Get
                Return ResourceManager.GetString("fcusb_Write", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Transfer speed.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_xferspeed() As String
            Get
                Return ResourceManager.GetString("fcusb_xferspeed", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
