'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class French
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FlashcatUSB.French", GetType(French).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Conseil la version du micrologiciel.
        '''</summary>
        Friend Shared ReadOnly Property cnts_avrver() As String
            Get
                Return ResourceManager.GetString("cnts_avrver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connecté à un appareil.
        '''</summary>
        Friend Shared ReadOnly Property cnts_device() As String
            Get
                Return ResourceManager.GetString("cnts_device", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nom de la mémoire Flash.
        '''</summary>
        Friend Shared ReadOnly Property cnts_flashname() As String
            Get
                Return ResourceManager.GetString("cnts_flashname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Taille de la mémoire flash.
        '''</summary>
        Friend Shared ReadOnly Property cnts_flashsize() As String
            Get
                Return ResourceManager.GetString("cnts_flashsize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type de mémoire Flash.
        '''</summary>
        Friend Shared ReadOnly Property cnts_flashtype() As String
            Get
                Return ResourceManager.GetString("cnts_flashtype", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mode de l&apos;appareil.
        '''</summary>
        Friend Shared ReadOnly Property cnts_mode() As String
            Get
                Return ResourceManager.GetString("cnts_mode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Script actif.
        '''</summary>
        Friend Shared ReadOnly Property cnts_script() As String
            Get
                Return ResourceManager.GetString("cnts_script", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erreur: Les données de fichiers hexadécimaux est plus grande que la taille de la mémoire DFU.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Effacement de la mémoire flash de AVR.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Envoi de commande d&apos;effacement AVR DFU.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_err3() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_err3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erreur: AVR éclair effacement a échoué.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_err4() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_err4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erreur: AVR éclair d&apos;écriture a échoué.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_err5() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_err5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AVR DFU commande réussie.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_sucess() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_sucess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AVR éclair écrit avec succès.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_writedone() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_writedone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nouveau firmware AVR programmé (&apos;appplication Démarrer&apos; cliquez pour commencer).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_writedonegui() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_writedonegui", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Début AVR d&apos;écriture flash ({0} octets).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avrwrite() As String
            Get
                Return ResourceManager.GetString("fcusb_avrwrite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adresse de base.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_baseaddress() As String
            Get
                Return ResourceManager.GetString("fcusb_baseaddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Annuler.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cancel() As String
            Get
                Return ResourceManager.GetString("fcusb_cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adresse de base de Flash: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_base() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_base", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Bus de bits {0}).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_bitbus() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_bitbus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description Flash: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_desc() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Opération d&apos;effacement FCI compléter!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_erasecomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_erasecomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Effacement CFI flash (ce qui pourrait prendre un moment).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_erasing() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_erasing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impossible d&apos;ouvrir le dispositif en mode JEDEC.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loaded CFI dispositif de flash compatible à l&apos;adresse: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_founddev() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_founddev", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modification des paramètres pour une partie existante: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_info1() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_info1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to interface.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_interface() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_interface", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash JEDEC ID: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_jedecid() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_jedecid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Le mode de programmation.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_pmode() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_pmode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Inconnu).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_unknown() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_unknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choisissez AVR firmware au programme.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_common_avrtoprog() As String
            Get
                Return ResourceManager.GetString("fcusb_common_avrtoprog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choisissez l&apos;emplacement pour enregistrer le journal de la console.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_console_save() As String
            Get
                Return ResourceManager.GetString("fcusb_console_save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Le périphérique connecté en mode bootloader DFU.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_conn() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_conn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fichier: pas de fichier a été chargé.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_file_default() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_file_default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chargez le fichier.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_loadfile() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_loadfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Programmez.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_progfile() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_progfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB prêt à fonctionner en mode DFU.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_ready() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Appplication Démarrer.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_startprog() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_startprog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Déconnecté de FlashcatUSB.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_disconnected() As String
            Get
                Return ResourceManager.GetString("fcusb_disconnected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erreur: Impossible de récupérer la version du micrologiciel conseil d&apos;administration.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to S&apos;il vous plaît mettre à jour firmware AVR à {0} ou plus récent.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB conseil d&apos;administration a dépassé firmware.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err3() As String
            Get
                Return ResourceManager.GetString("fcusb_err3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB pas se connecter à la carte cible en utilisant JTAG.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err4() As String
            Get
                Return ResourceManager.GetString("fcusb_err4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impossible de définir la valeur (entrée non valide).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err5() As String
            Get
                Return ResourceManager.GetString("fcusb_err5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impossible de définir la valeur (la valeur est supérieure à un octet).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err6() As String
            Get
                Return ResourceManager.GetString("fcusb_err6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impossible de définir la valeur (valeur est plus grande que quatre octets).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err7() As String
            Get
                Return ResourceManager.GetString("fcusb_err7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erreur: le fichier est corrompu ou non d&apos;un fichier Hex AVR.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err8() As String
            Get
                Return ResourceManager.GetString("fcusb_err8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fichier: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_file() As String
            Get
                Return ResourceManager.GetString("fcusb_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L&apos;utilisateur a annulé. Aucune donnée n&apos;a été enregistrée.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_filesave_canceled() As String
            Get
                Return ResourceManager.GetString("fcusb_filesave_canceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} sauvegardé avec succès sur le disque.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_filesave_sucess() As String
            Get
                Return ResourceManager.GetString("fcusb_filesave_sucess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Données converties dans un format de lecture Intel hex pour sauver.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_filesave_tohex() As String
            Get
                Return ResourceManager.GetString("fcusb_filesave_tohex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choisissez l&apos;emplacement du disque dur et le format des données de sortie.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_filesave_type() As String
            Get
                Return ResourceManager.GetString("fcusb_filesave_type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impossible d&apos;écrire les données à l&apos;appareil flash (en dehors des limites).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_flasherr1() As String
            Get
                Return ResourceManager.GetString("fcusb_flasherr1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fichier: pas de fichier actuellement chargé.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_hex_nofile() As String
            Get
                Return ResourceManager.GetString("fcusb_hex_nofile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Initialisation du moteur EJTAG.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_initjtag() As String
            Get
                Return ResourceManager.GetString("fcusb_initjtag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Le périphérique connecté en mode JTAG: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_conn() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_conn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: commande de réinitialisation envoyé processeur.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_cpureset() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_cpureset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: Processeur entré en mode de débogage.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_debugon() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_debugon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Périphérique cible prend en charge le mode DMA.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_dma() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_dma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Effacer le fonctionnement complet!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_erasecomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_erasecomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erreur de connexion à la carte cible.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impossible de se connecter à EJTAG dispositif.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dispositif de flash à l&apos;adresse: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_foundat() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_foundat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FCI: Trouvé dispositif de flash compatible à l&apos;adresse: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_foundcfi() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_foundcfi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: augmenter la taille IR à {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_irlen() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_irlen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dispositif cible ne prend pas en charge le mode DMA.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_nodma() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_nodma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Support Flash n&apos;a pu être trouvée.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_notfound() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_notfound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: appareil prend en charge que non-dma (PrAcc) et le mode non-pracc firmware est chargé dans FlashcatUSB.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_praccmode() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_praccmode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prêt à fonctionner FlashcatUSB dans JTAG mode de.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_ready() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recherche de la CFIconforme flash dispositif.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_searchcfi() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_searchcfi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recherche d&apos;un @ CFI flash {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_searchcfiat() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_searchcfiat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: SPI Flash détectée ({0}).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_spidetected() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_spidetected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Effacement complet SPI flash (ce qui pourrait prendre un moment).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_spierasing() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_spierasing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: SPI registre retourné {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_spiregret() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_spiregret", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configuration moteur JTAG avec succès.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtagsetup() As String
            Get
                Return ResourceManager.GetString("fcusb_jtagsetup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Longueur.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_length() As String
            Get
                Return ResourceManager.GetString("fcusb_length", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La version LibUsbDotNet: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_libusb_ver() As String
            Get
                Return ResourceManager.GetString("fcusb_libusb_ver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adresse.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_address() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_address", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L&apos;utilisateur a annulé l&apos;opération d&apos;écriture.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_cancelled() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_cancelled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choisir un fichier à écrire dans {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_choosefile() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_choosefile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erreur, le fichier n&apos;existe pas ou ne contient pas de données.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erreur lors de la tentative de lecture de données.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fichier choisi, en écriture {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_filechosen() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_filechosen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fichier ouvert en écriture: {0} (format hexadécimal binaire), la taille totale du fichier: {1} octets.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_opened_bin() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_opened_bin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fichier ouvert en écriture: {0} (format hexadécimal Intel), la taille totale du fichier: {1} octets.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_opened_intel() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_opened_intel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lire opération annulée.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_readcanceled() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_readcanceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lire compléter, s&apos;il vous plaît choisir le type d&apos;emplacement et le format.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_readcomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_readcomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sélectionnez la plage à lire à partir de {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_readfrom() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_readfrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Début de mémoire opération de lecture.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_readstart() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_readstart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sélectionnez la plage d&apos;écrire des données {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_selectwriterange() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_selectwriterange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L&apos;utilisateur a annulé l&apos;opération de lecture.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_usercanceledread() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_usercanceledread", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L&apos;utilisateur a annulé. Pas de données écrites à {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_usercanwrite() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_usercanwrite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash plus d&apos;écriture opération annulée.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_writecanceled() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_writecanceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L&apos;opération d&apos;écriture complète: {0} octets écrite..
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_writecomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_writecomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Début opération d&apos;écriture de mémoire.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_writestart() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_writestart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L&apos;écriture du fichier {0} en {1} ({2} octets à écrire).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_writing() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_writing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dispositif de mémoire.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memdev() As String
            Get
                Return ResourceManager.GetString("fcusb_memdev", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Début de mémoire lu à partir de {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_beginread() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_beginread", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Effacement en vrac pas pris en charge pour les dispositifs DRAM.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_dram_notsup() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_dram_notsup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MemoryInit: Impossible - paramètres de l&apos;appareil n&apos;a pas Init.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impossible de détecter SPI flash (API non chargée pour le courant MCU).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MemoryInit: Échec - Impossible de se connecter à l&apos;interface de mémoire PrAcc (firmware AVR ne prend pas en charge).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_nopraccsupport() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_nopraccsupport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L&apos;opération de lecture complète.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_readdone() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_readdone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adresse de départ: Longueur {0} ({1}): {2} &quot;.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_startaddr() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_startaddr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verifing données écrites à {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_verify() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_verify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erreur: Flash vérifier lire un nombre incorrect d&apos;octets.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_verifyerr1() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_verifyerr1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adresse {0}: {1} a écrit et de lecture {2} ({3} décalages).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_verifyerr2() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_verifyerr2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erreur: la vérification des données à {0} a échoué!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_verifyfailed() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_verifyfailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La vérification des données a été un succès.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_verifyokay() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_verifyokay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impossible d&apos;écrire des données (dispositif est en lecture seule).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_write_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_write_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rédaction adresse {0} {1} avec octets ({2}).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_writeaddr() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_writeaddr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L&apos;opération d&apos;écriture flash complet!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_writecomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_writecomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L&apos;opération d&apos;écriture terminée, {0} octets écrite..
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_writedone() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_writedone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} octets écrits dans {1} secondes, {2} octets par seconde.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_writespeed() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_writespeed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AVR Firmware.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_avrfw() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_avrfw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Console.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_console() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_console", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Script courant.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_cscript() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_cscript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Détecter dispositif.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_detectdevice() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_detectdevice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sortie.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_exit() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_exit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Langue.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_language() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_language", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Script de chargement.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_loadscript() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_loadscript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Principal.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_main() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_main", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scénario.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_script() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_script", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paramètres.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_settings() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Utiliser les paramètres automatiques.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_auto() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_auto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Commandez bits.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_bitorder() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_bitorder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Effacer Chip.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_chiperase() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_chiperase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Taille de la puce.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_chipsize() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_chipsize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Diviseur d&apos;horloge.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_clodiv() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_clodiv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Commandes de périphériques SPI.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_devcmds() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_devcmds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Activer Ecrire statut.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_enwrstatus() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_enwrstatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Taille Effacer.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_erasesize() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_erasesize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Utilisez les valeurs communément trouvés dans la fiche technique de l&apos;appareil.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_info() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mode Programme.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_pmode() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_pmode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Programme des pages.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_pp() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_pp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lire.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_read() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_read", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lire l&apos;état.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_rstatus() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_rstatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Effacer secteur.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_serase() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_serase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI mode.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_spimode() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_spimode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Utilisez ces paramètres.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_usesettings() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_usesettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Utilisez &apos;Activer Ecrire État.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_usewren() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_usewren", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ecrire Activer.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_we() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_we", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ecrire statut.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_wstatus() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_wstatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paramètres SPI.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spisettings() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spisettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Statut.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_status() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Décharger le script.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_unloadscript() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_unloadscript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vérifiez la programmation.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_verify() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_verify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Le périphérique connecté dans la NAND sur le mode SPI.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nand_conn() As String
            Get
                Return ResourceManager.GetString("fcusb_nand_conn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB prêt à fonctionner en mode NON-ET.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nand_ready() As String
            Get
                Return ResourceManager.GetString("fcusb_nand_ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nouvelle programmation AVR firmware.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_newavrfw() As String
            Get
                Return ResourceManager.GetString("fcusb_newavrfw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Pas de flash détecté).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_noflash() As String
            Get
                Return ResourceManager.GetString("fcusb_noflash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Les données correctement lus et analysés.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_dataread() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_dataread", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erreur: Aucune zone CFG trouvé!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erreur lors du chargement de données non-vol.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Pas trouvé).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_notfound() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_notfound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La lecture des données de configuration non-vol.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_readingnonvol() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_readingnonvol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rédaction non-vol de configuration au format Flash.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_writing() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_writing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Terminé. Non-vol config à jour.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_wrote() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_wrote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_okbutton() As String
            Get
                Return ResourceManager.GetString("fcusb_okbutton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gamme:.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_range() As String
            Get
                Return ResourceManager.GetString("fcusb_range", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lire.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_Read() As String
            Get
                Return ResourceManager.GetString("fcusb_Read", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fonctionnant sur: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_running() As String
            Get
                Return ResourceManager.GetString("fcusb_running", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vérification d&apos;un script dispositif spécifique pour charger automatiquement.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_check() As String
            Get
                Return ResourceManager.GetString("fcusb_script_check", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Script chargé {0} avec succès.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_loaded() As String
            Get
                Return ResourceManager.GetString("fcusb_script_loaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chargement de script dispositif spécifique: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_loading() As String
            Get
                Return ResourceManager.GetString("fcusb_script_loading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pas de fichiers de script disponibles.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_none() As String
            Get
                Return ResourceManager.GetString("fcusb_script_none", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impossible de charger le script (fichier n&apos;existe pas).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_notexist() As String
            Get
                Return ResourceManager.GetString("fcusb_script_notexist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sélectionnez le fichier de script pour ouvrir FlashcatUSB.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_open() As String
            Get
                Return ResourceManager.GetString("fcusb_script_open", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Le script {0} a été déchargé.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_unload() As String
            Get
                Return ResourceManager.GetString("fcusb_script_unload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connecté à Flash.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_connflash() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_connflash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pour lire écrire contact@embeddedcomputers.net support par email avec JEDEC ID.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_email() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash erase compléter dans {0} secondes.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_erasecomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_erasecomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Effacement périphérique flash ensemble, la taille totale: {0} octets (cela peut prendre un moment).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_erasingbulk() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_erasingbulk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB connecté en mode SPI, mais pas de Flash détectée.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB détecté dispositif SPI, mais ce n&apos;est pas actuellement pris en charge.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La taille du périphérique SPI doit être d&apos;au moins un mégabit.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_err3() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_err3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La taille du périphérique SPI doit être un multiple d&apos;un mégabit.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_err4() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_err4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Impossible de se connecter à un appareil compatible SPI.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_err5() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_err5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash détecté: {0} ({1} octets).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_flashdetected() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_flashdetected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erreur de paramétrage de SPI, mode non pris en charge: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_modenotsupported() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_modenotsupported", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI mode de réglage automatique de configurer.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_modesetauto() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_modesetauto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI mode réglé sur {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_modesetto() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_modesetto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dispositif d&apos;ouverture dans SPI mode.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_openinmode() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_openinmode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Programmation en mode: SPI (haute vitesse).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_progmode() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_progmode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB prête pour exploitation dans les SPI mode de.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_ready() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Numérisation pour Flash SPI.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_scanning() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_scanning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Utilisation des paramètres personnalisés à partir de la page Paramètres SPI.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_usingcustom() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_usingcustom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Le périphérique connecté au mode SPI, la version de firmware: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_ver() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_ver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to État FlashcatUSB: Connecté.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_status_connected() As String
            Get
                Return ResourceManager.GetString("fcusb_status_connected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to État FlashcatUSB: Déconnecté.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_status_disconnect() As String
            Get
                Return ResourceManager.GetString("fcusb_status_disconnect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to STOP.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_stop() As String
            Get
                Return ResourceManager.GetString("fcusb_stop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Logiciel d&apos;attente pour que l&apos;appareil soit connecté via USB.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_waitingforusb() As String
            Get
                Return ResourceManager.GetString("fcusb_waitingforusb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bienvenue dans le logiciel d&apos;interfaçage FlashcatUSB, construire: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_welcome() As String
            Get
                Return ResourceManager.GetString("fcusb_welcome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bienvenue à FlashcatUSB!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_welcome_status() As String
            Get
                Return ResourceManager.GetString("fcusb_welcome_status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Écrire.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_Write() As String
            Get
                Return ResourceManager.GetString("fcusb_Write", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vitesse.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_xferspeed() As String
            Get
                Return ResourceManager.GetString("fcusb_xferspeed", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
