'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class German
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FlashcatUSB.German", GetType(German).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Foren-Firmware-Version.
        '''</summary>
        Friend Shared ReadOnly Property cnts_avrver() As String
            Get
                Return ResourceManager.GetString("cnts_avrver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verbunden mit Gerät.
        '''</summary>
        Friend Shared ReadOnly Property cnts_device() As String
            Get
                Return ResourceManager.GetString("cnts_device", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash-Speicher-Namen.
        '''</summary>
        Friend Shared ReadOnly Property cnts_flashname() As String
            Get
                Return ResourceManager.GetString("cnts_flashname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash-Speichergröße.
        '''</summary>
        Friend Shared ReadOnly Property cnts_flashsize() As String
            Get
                Return ResourceManager.GetString("cnts_flashsize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash-Speicher-Typ.
        '''</summary>
        Friend Shared ReadOnly Property cnts_flashtype() As String
            Get
                Return ResourceManager.GetString("cnts_flashtype", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Geräte-Modus.
        '''</summary>
        Friend Shared ReadOnly Property cnts_mode() As String
            Get
                Return ResourceManager.GetString("cnts_mode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aktiv-Skript.
        '''</summary>
        Friend Shared ReadOnly Property cnts_script() As String
            Get
                Return ResourceManager.GetString("cnts_script", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fehler: Die Hex-Datei Daten größer ist als die Größe des DFU-Speicher.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Löschen der AVR Flash-Speicher.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Senden AVR DFU Löschbefehl.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_err3() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_err3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fehler: AVR Flash Erase gescheitert.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_err4() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_err4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fehler: AVR Flash Schreiben, ist fehlgeschlagen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_err5() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_err5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AVR DFU Befehl erfolgreich.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_sucess() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_sucess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AVR Flash geschrieben erfolgreich.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_writedone() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_writedone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Neuer AVR Firmware programmiert werden (klicken Sie auf &apos;Start Anwendungssuche&apos; zu beginnen).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_writedonegui() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_writedonegui", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Beginnend AVR Flash Schreiben ({0} Bytes).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avrwrite() As String
            Get
                Return ResourceManager.GetString("fcusb_avrwrite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Basisadresse.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_baseaddress() As String
            Get
                Return ResourceManager.GetString("fcusb_baseaddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stornieren.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cancel() As String
            Get
                Return ResourceManager.GetString("fcusb_cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash-Basis-Adresse: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_base() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_base", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ({0} Bit-Bus).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_bitbus() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_bitbus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash-Beschreibung: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_desc() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CFI Löschvorgang zu vervollständigen!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_erasecomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_erasecomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Löschen von Flash-CFI (dies könnte einen Moment dauern).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_erasing() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_erasing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Konnte Gerät in JEDEC-Modus öffnen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Installiert CFI kompatible Flash-Gerät auf: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_founddev() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_founddev", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ändern Parameter für bestehende Teil: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_info1() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_info1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schnittstelle.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_interface() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_interface", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash-JEDEC-ID: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_jedecid() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_jedecid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Programmiermodus.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_pmode() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_pmode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Unbekannt).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_unknown() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_unknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wählen AVR Firmware-Programm.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_common_avrtoprog() As String
            Get
                Return ResourceManager.GetString("fcusb_common_avrtoprog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wählen Sie einen Standort, um die Konsole Protokoll speichern.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_console_save() As String
            Get
                Return ResourceManager.GetString("fcusb_console_save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gerät in den DFU-Bootloader-Modus geschaltet.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_conn() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_conn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Datei: Nein geladen wurde.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_file_default() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_file_default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Datei laden.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_loadfile() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_loadfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Programm die Daten.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_progfile() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_progfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB betriebsbereit in den DFU-Modus.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_ready() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start Anwendungssuche.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_startprog() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_startprog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Abgetrennt von FlashcatUSB.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_disconnected() As String
            Get
                Return ResourceManager.GetString("fcusb_disconnected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fehler beim Firmware-Version abrufen Bord.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bitte aktualisieren AVR-Firmware auf {0} oder neuer.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB Bord hat Firmware veraltet.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err3() As String
            Get
                Return ResourceManager.GetString("fcusb_err3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB versäumt, eine Verbindung zum Ziel mittels JTAG-Board.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err4() As String
            Get
                Return ResourceManager.GetString("fcusb_err4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kann Wert (ungültige Eingabe) gesetzt.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err5() As String
            Get
                Return ResourceManager.GetString("fcusb_err5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kann Wert (Wert ist größer als ein Byte) gesetzt.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err6() As String
            Get
                Return ResourceManager.GetString("fcusb_err6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kann Wert (Wert ist größer als vier Bytes) gesetzt.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err7() As String
            Get
                Return ResourceManager.GetString("fcusb_err7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fehler: Datei ist beschädigt oder kein AVR Hex-Datei.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err8() As String
            Get
                Return ResourceManager.GetString("fcusb_err8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Datei: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_file() As String
            Get
                Return ResourceManager.GetString("fcusb_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Benutzer abgebrochen. Es wurden keine Daten gespeichert.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_filesave_canceled() As String
            Get
                Return ResourceManager.GetString("fcusb_filesave_canceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} erfolgreich auf der Festplatte gespeichert.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_filesave_sucess() As String
            Get
                Return ResourceManager.GetString("fcusb_filesave_sucess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Konvertierten Daten in Intel hex Format zum Speichern lesen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_filesave_tohex() As String
            Get
                Return ResourceManager.GetString("fcusb_filesave_tohex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wählen Sie Speicherort auf der Festplatte und Output-Daten-Format.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_filesave_type() As String
            Get
                Return ResourceManager.GetString("fcusb_filesave_type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kann Daten auf Flash-Gerät zu schreiben (out of bounds).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_flasherr1() As String
            Get
                Return ResourceManager.GetString("fcusb_flasherr1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Datei: Nein aktuell geladenen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_hex_nofile() As String
            Get
                Return ResourceManager.GetString("fcusb_hex_nofile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Initialisieren EJTAG Motor.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_initjtag() As String
            Get
                Return ResourceManager.GetString("fcusb_initjtag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Geräte im JTAG-Modus geschaltet: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_conn() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_conn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: Prozessor geschickt Reset-Befehl.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_cpureset() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_cpureset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: Prozessor trat in den Debug-Modus.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_debugon() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_debugon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zielgerät unterstützt DMA-Modus.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_dma() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_dma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Löschvorgang abgeschlossen!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_erasecomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_erasecomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fehler beim Verbinden mit Brett zielen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Es konnte keine Verbindung zum Gerät EJTAG.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash-Gerät zu Hause: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_foundat() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_foundat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CFI: Found kompatible Flash-Gerät auf: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_foundcfi() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_foundcfi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: IR Länge auf {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_irlen() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_irlen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zielgerät nicht unterstützt DMA-Modus.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_nodma() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_nodma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash-Gerät konnte nicht gefunden werden.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_notfound() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_notfound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: Gerät unterstützt nur nicht-DMA (PrAcc)-Modus und nicht-pracc Firmware wird geladen FlashcatUSB.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_praccmode() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_praccmode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB betriebsbereit im JTAG-Modus.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_ready() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Auf der Suche nach CFI kompatible Flash-Medium.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_searchcfi() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_searchcfi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Suche nach einem CFI-Flash @ {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_searchcfiat() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_searchcfiat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: SPI Flash-Speicher gefunden ({0}).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_spidetected() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_spidetected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Löschen gesamten SPI-Flash (dies könnte einen Moment dauern).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_spierasing() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_spierasing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: SPI-Register zurückgegeben {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_spiregret() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_spiregret", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG-Engine Setup erfolgreich.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtagsetup() As String
            Get
                Return ResourceManager.GetString("fcusb_jtagsetup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Länge.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_length() As String
            Get
                Return ResourceManager.GetString("fcusb_length", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LibUsbDotNet Version: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_libusb_ver() As String
            Get
                Return ResourceManager.GetString("fcusb_libusb_ver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adresse.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_address() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_address", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Benutzer abgebrochen Schreib-Operation.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_cancelled() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_cancelled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wählen Sie Datei zu schreiben, in {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_choosefile() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_choosefile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fehler, keine Datei nicht vorhanden oder enthält keine Daten.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fehler beim Versuch, Daten zu lesen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gewählt, in writting Datei {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_filechosen() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_filechosen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eröffnet Datei zum Schreiben: {0} (binäre Hex-Format), Gesamtgröße der Datei: {1} Bytes.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_opened_bin() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_opened_bin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eröffnet Datei zum Schreiben: {0} (Intel Hex-Format), Gesamtgröße der Datei: {1} Bytes.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_opened_intel() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_opened_intel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lesen Vorgang abgebrochen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_readcanceled() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_readcanceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lesen Sie die vollständige, wählen Sie bitte Ort und Format-Typ.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_readcomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_readcomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wählen Bereich von {0} gelesen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_readfrom() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_readfrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Beginnend Speicher Lese-Operation.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_readstart() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_readstart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wählen Sie Auswahl, um Daten zu schreiben {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_selectwriterange() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_selectwriterange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Benutzer abgebrochen Lesevorgang.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_usercanceledread() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_usercanceledread", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Benutzer abgebrochen. Es liegen keine Daten geschrieben, um {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_usercanwrite() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_usercanwrite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash-Schreib-Operation abgesagt.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_writecanceled() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_writecanceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schreib-Operation abgeschlossen: {0} Bytes geschrieben..
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_writecomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_writecomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zum Anfang Speicher-Schreib-Operation.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_writestart() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_writestart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schreiben von Datei {0} in {1} ({2} zu schreibenden Bytes).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_writing() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_writing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Speichervorrichtung.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memdev() As String
            Get
                Return ResourceManager.GetString("fcusb_memdev", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Beginnend Speicher von {0} gelesen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_beginread() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_beginread", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bulk-Erase nicht für DRAM-Geräten unterstützt.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_dram_notsup() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_dram_notsup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MemoryInit: Failed - Geräteparameter gescheitert Init.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kann nicht erkennen, SPI-Flash (API nicht für aktuelle MCU geladen).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MemoryInit: Gescheitert - Keine Verbindung zum PrAcc Speicher-Interface (AVR-Firmware nicht unterstützt) verbinden.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_nopraccsupport() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_nopraccsupport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lesen Operation abgeschlossen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_readdone() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_readdone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Startadresse: {0} ({1}) Länge: {2} &quot;.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_startaddr() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_startaddr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verifing geschriebenen Daten unter {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_verify() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_verify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fehler: Flash überprüfen las eine falsche Anzahl von Bytes.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_verifyerr1() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_verifyerr1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adresse {0}: {1} schrieb und las {2} ({3} Mismatches).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_verifyerr2() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_verifyerr2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fehler: Datenüberprüfung bei {0} ist fehlgeschlagen!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_verifyfailed() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_verifyfailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Die Verifizierung der Daten erfolgreich war.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_verifyokay() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_verifyokay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Daten können nicht schreiben (Gerät ist read-only).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_write_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_write_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schreiben von Adresse {0} mit {1} Bytes ({2}).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_writeaddr() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_writeaddr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schreiben Sie den Flash-Vorgang abgeschlossen!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_writecomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_writecomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schreib-Operation abgeschlossen, geschrieben {0} Bytes..
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_writedone() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_writedone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} Bytes in {1} Sekunden geschrieben, {2} Bytes / s.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_writespeed() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_writespeed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AVR-Firmware.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_avrfw() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_avrfw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Konsole.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_console() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_console", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aktuelle Skript.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_cscript() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_cscript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Entdecken Gerät.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_detectdevice() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_detectdevice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ausgang.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_exit() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_exit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sprache.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_language() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_language", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ladeskript.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_loadscript() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_loadscript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Main.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_main() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_main", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skript.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_script() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_script", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Einstellungen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_settings() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Automatische Einstellungen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_auto() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_auto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bit-Reihenfolge.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_bitorder() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_bitorder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chip Löschen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_chiperase() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_chiperase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chip Größe.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_chipsize() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_chipsize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Taktteiler.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_clodiv() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_clodiv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI Gerät Befehle.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_devcmds() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_devcmds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enable Write-Status.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_enwrstatus() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_enwrstatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Erase Größe.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_erasesize() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_erasesize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verwenden Sie die Werte häufig in den Geräte-Datenblatt gefunden.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_info() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Programm-Modus.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_pmode() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_pmode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seite Programm.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_pp() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_pp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lesen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_read() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_read", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status lesen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_rstatus() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_rstatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sektor Löschen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_serase() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_serase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI-Modus.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_spimode() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_spimode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Manuelle Einstellungen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_usesettings() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_usesettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verwenden Sie &apos;Schreib-Status ermöglichen&apos;.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_usewren() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_usewren", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schreiben Sie Enable.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_we() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_we", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schreib-Status.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_wstatus() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_wstatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI-Einstellungen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spisettings() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spisettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_status() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Entladeskript.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_unloadscript() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_unloadscript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Überprüfen Sie die Programmierung.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_verify() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_verify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Geräte in NAND über SPI-Modus geschaltet.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nand_conn() As String
            Get
                Return ResourceManager.GetString("fcusb_nand_conn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB betriebsbereit in NAND-Modus.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nand_ready() As String
            Get
                Return ResourceManager.GetString("fcusb_nand_ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Programmierung neuer AVR-Firmware.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_newavrfw() As String
            Get
                Return ResourceManager.GetString("fcusb_newavrfw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Kein Blitz erkannt).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_noflash() As String
            Get
                Return ResourceManager.GetString("fcusb_noflash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Daten erfolgreich gelesen und analysiert.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_dataread() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_dataread", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fehler: Keine CFG Bereich gefunden!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fehler beim Laden Non-Vol Daten.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Nicht gefunden).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_notfound() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_notfound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reading Non-Vol-Konfigurationsdaten.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_readingnonvol() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_readingnonvol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Writing Non-Band-Konfiguration zu Flash.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_writing() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_writing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fertig. Non-Vol Config aktualisiert.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_wrote() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_wrote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_okbutton() As String
            Get
                Return ResourceManager.GetString("fcusb_okbutton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reichweite:.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_range() As String
            Get
                Return ResourceManager.GetString("fcusb_range", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lesen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_Read() As String
            Get
                Return ResourceManager.GetString("fcusb_Read", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Laufen auf: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_running() As String
            Get
                Return ResourceManager.GetString("fcusb_running", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Suchen nach einem bestimmten Gerät Skript automatisch zu laden.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_check() As String
            Get
                Return ResourceManager.GetString("fcusb_script_check", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loaded skript {0} erfolgreich.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_loaded() As String
            Get
                Return ResourceManager.GetString("fcusb_script_loaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ladevorrichtung spezifische Skript: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_loading() As String
            Get
                Return ResourceManager.GetString("fcusb_script_loading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keine Skript-Dateien verfügbar.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_none() As String
            Get
                Return ResourceManager.GetString("fcusb_script_none", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Skript kann nicht geladen werden (Datei nicht vorhanden ist).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_notexist() As String
            Get
                Return ResourceManager.GetString("fcusb_script_notexist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wählen FlashcatUSB Skript-Datei zu öffnen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_open() As String
            Get
                Return ResourceManager.GetString("fcusb_script_open", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Das Skript {0} wurde entladen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_unload() As String
            Get
                Return ResourceManager.GetString("fcusb_script_unload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verbunden mit Flash.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_connflash() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_connflash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Für Lese-Schreib-Support per E-Mail contact@embeddedcomputers.net mit JEDEC-ID.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_email() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash Erase in {0} Sekunden abgeschlossen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_erasecomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_erasecomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Löschen ganzer Flash-Gerät, Gesamtgröße: {0} Bytes (dies kann einen Moment dauern).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_erasingbulk() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_erasingbulk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB im SPI-Modus angeschlossen, aber kein Flash erkannt.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB erkannt SPI Devices, sondern seine Zeit noch nicht unterstützt.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI Gerätegröße muss mindestens ein Megabit sein.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_err3() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_err3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI-Gerät muss ein Vielfaches von einem Megabit sein.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_err4() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_err4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Keine Verbindung zum kompatiblen Gerät verbinden SPI.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_err5() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_err5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash-Speicher gefunden: {0} ({1} Bytes).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_flashdetected() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_flashdetected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fehler beim Festlegen des SPI-Modus, Modus nicht unterstützt: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_modenotsupported() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_modenotsupported", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI-Modus auf auto konfigurieren.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_modesetauto() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_modesetauto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI-Modus auf {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_modesetto() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_modesetto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Öffnungsvorrichtung im SPI-Modus.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_openinmode() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_openinmode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Programmiermodus: SPI (schnell-Modus).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_progmode() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_progmode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB betriebsbereit im SPI-Modus.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_ready() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Scannen für SPI-Flash.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_scanning() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_scanning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mit benutzerdefinierten Einstellungen von SPI Seite Einstellungen.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_usingcustom() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_usingcustom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Geräte im SPI-Modus, Firmware-Version verbunden sind: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_ver() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_ver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB Status: Verbunden.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_status_connected() As String
            Get
                Return ResourceManager.GetString("fcusb_status_connected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB Status: Getrennt.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_status_disconnect() As String
            Get
                Return ResourceManager.GetString("fcusb_status_disconnect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HALT.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_stop() As String
            Get
                Return ResourceManager.GetString("fcusb_stop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Software warten, bis das Gerät über USB angeschlossen werden.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_waitingforusb() As String
            Get
                Return ResourceManager.GetString("fcusb_waitingforusb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Willkommen bei FlashcatUSB Schnittstellen-Software, bauen: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_welcome() As String
            Get
                Return ResourceManager.GetString("fcusb_welcome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Willkommen bei FlashcatUSB!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_welcome_status() As String
            Get
                Return ResourceManager.GetString("fcusb_welcome_status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schreiben.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_Write() As String
            Get
                Return ResourceManager.GetString("fcusb_Write", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Geschwindigkeit.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_xferspeed() As String
            Get
                Return ResourceManager.GetString("fcusb_xferspeed", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
