'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Spanish
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FlashcatUSB.Spanish", GetType(Spanish).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consejo de la versión de firmware.
        '''</summary>
        Friend Shared ReadOnly Property cnts_avrver() As String
            Get
                Return ResourceManager.GetString("cnts_avrver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Conectado a dispositivo.
        '''</summary>
        Friend Shared ReadOnly Property cnts_device() As String
            Get
                Return ResourceManager.GetString("cnts_device", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nombre de la memoria flash.
        '''</summary>
        Friend Shared ReadOnly Property cnts_flashname() As String
            Get
                Return ResourceManager.GetString("cnts_flashname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tamaño de la memoria flash.
        '''</summary>
        Friend Shared ReadOnly Property cnts_flashsize() As String
            Get
                Return ResourceManager.GetString("cnts_flashsize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tipo de memoria flash.
        '''</summary>
        Friend Shared ReadOnly Property cnts_flashtype() As String
            Get
                Return ResourceManager.GetString("cnts_flashtype", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dispositivo de modo de.
        '''</summary>
        Friend Shared ReadOnly Property cnts_mode() As String
            Get
                Return ResourceManager.GetString("cnts_mode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Secuencia de comandos activa.
        '''</summary>
        Friend Shared ReadOnly Property cnts_script() As String
            Get
                Return ResourceManager.GetString("cnts_script", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: Los datos de archivo hexagonales es más grande que el tamaño de la memoria DFU.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Borrado de la memoria flash de AVR.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El envío de AVR comando de borrado DFU.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_err3() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_err3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: AVR borrado de flash no.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_err4() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_err4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: AVR Flash de escritura no.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_err5() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_err5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AVR DFU éxito de comandos.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_sucess() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_sucess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AVR Flash escrito con éxito.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_writedone() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_writedone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nuevo firmware AVR programado (haga clic en &apos;Inicio de aplicación&apos; para comenzar).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avr_writedonegui() As String
            Get
                Return ResourceManager.GetString("fcusb_avr_writedonegui", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A partir del AVR Flash de escritura ({0} bytes).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_avrwrite() As String
            Get
                Return ResourceManager.GetString("fcusb_avrwrite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Base de la dirección.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_baseaddress() As String
            Get
                Return ResourceManager.GetString("fcusb_baseaddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancelar.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cancel() As String
            Get
                Return ResourceManager.GetString("fcusb_cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash Dirección base: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_base() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_base", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ({0} bus bits).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_bitbus() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_bitbus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Descripción de Flash: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_desc() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_desc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Operación de borrado de TPI completar!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_erasecomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_erasecomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Borrado de CFI flash (esto puede tomar un momento).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_erasing() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_erasing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se pudo abrir el dispositivo en el modo de JEDEC.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cargado CFI dispositivo de memoria flash compatibles en: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_founddev() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_founddev", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cambio de parámetros para una parte ya existente: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_info1() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_info1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to interfaz.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_interface() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_interface", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash JEDEC ID: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_jedecid() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_jedecid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modo de programación.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_pmode() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_pmode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Desconocido).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_cfi_unknown() As String
            Get
                Return ResourceManager.GetString("fcusb_cfi_unknown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Elegir AVR firmware para el programa.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_common_avrtoprog() As String
            Get
                Return ResourceManager.GetString("fcusb_common_avrtoprog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Elija un lugar para guardar el registro de la consola.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_console_save() As String
            Get
                Return ResourceManager.GetString("fcusb_console_save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El dispositivo conectado en modo bootloader DFU.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_conn() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_conn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Archivo: no hay ningún archivo se ha cargado.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_file_default() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_file_default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cargar archivo.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_loadfile() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_loadfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Programa.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_progfile() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_progfile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB listo para funcionar en modo DFU.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_ready() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inicio de aplicación.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_dfu_startprog() As String
            Get
                Return ResourceManager.GetString("fcusb_dfu_startprog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Desconectado de FlashcatUSB.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_disconnected() As String
            Get
                Return ResourceManager.GetString("fcusb_disconnected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: no pudo recuperar la versión firmware de la tarjeta.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Por favor, actualizar el firmware de AVR a {0} o posterior.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB junta ha desactualizado firmware.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err3() As String
            Get
                Return ResourceManager.GetString("fcusb_err3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB no pudo conectarse al dirigirse a bordo utilizando JTAG.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err4() As String
            Get
                Return ResourceManager.GetString("fcusb_err4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se puede establecer el valor (de entrada no válido).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err5() As String
            Get
                Return ResourceManager.GetString("fcusb_err5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se puede establecer el valor (el valor es más grande que un byte).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err6() As String
            Get
                Return ResourceManager.GetString("fcusb_err6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se puede establecer el valor (el valor es mayor que cuatro bytes).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err7() As String
            Get
                Return ResourceManager.GetString("fcusb_err7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: el archivo está dañado o no es un archivo Hex AVR.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_err8() As String
            Get
                Return ResourceManager.GetString("fcusb_err8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Archivo: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_file() As String
            Get
                Return ResourceManager.GetString("fcusb_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El usuario ha cancelado. No hay datos se ha guardado.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_filesave_canceled() As String
            Get
                Return ResourceManager.GetString("fcusb_filesave_canceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} guardado con éxito en el disco.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_filesave_sucess() As String
            Get
                Return ResourceManager.GetString("fcusb_filesave_sucess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Leer los datos convertidos a formato hex de Intel para el ahorro.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_filesave_tohex() As String
            Get
                Return ResourceManager.GetString("fcusb_filesave_tohex", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleccione la ubicación del disco duro y formato de salida de datos.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_filesave_type() As String
            Get
                Return ResourceManager.GetString("fcusb_filesave_type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se puede escribir datos al dispositivo de memoria flash (fuera de límites).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_flasherr1() As String
            Get
                Return ResourceManager.GetString("fcusb_flasherr1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Archivo: no hay ningún archivo actualmente cargado.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_hex_nofile() As String
            Get
                Return ResourceManager.GetString("fcusb_hex_nofile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Inicialización del motor EJTAG.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_initjtag() As String
            Get
                Return ResourceManager.GetString("fcusb_initjtag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El dispositivo conectado en el modo JTAG: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_conn() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_conn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: comando enviado reinicio del procesador.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_cpureset() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_cpureset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: Procesador entró en modo de depuración.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_debugon() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_debugon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dispositivo de destino compatible con el modo DMA.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_dma() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_dma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Borrar el funcionamiento completo!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_erasecomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_erasecomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error de conexión con destino Junta.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error al conectar con el dispositivo EJTAG.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dispositivo de memoria flash en: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_foundat() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_foundat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CFI: Se encuentra en el dispositivo de memoria flash compatibles: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_foundcfi() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_foundcfi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: conjunto de infrarrojos de longitud de {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_irlen() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_irlen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dispositivo de destino no admite el modo DMA.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_nodma() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_nodma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dispositivo de memoria flash no se pudo encontrar.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_notfound() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_notfound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: El dispositivo sólo es compatible con la no-DMA (PrAcc) el modo y el firmware no se carga en pracc FlashcatUSB.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_praccmode() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_praccmode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Listo para la operación FlashcatUSB en JTAG modo.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_ready() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Búsqueda de TPI dispositivo compatible con flash.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_searchcfi() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_searchcfi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Búsqueda de un Tribunal de Primera Instancia de Flash @ {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_searchcfiat() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_searchcfiat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: SPI Flash detectado ({0}).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_spidetected() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_spidetected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Borrado de todo el SPI Flash (esto puede tomar un momento).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_spierasing() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_spierasing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG: SPI registro devuelto {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtag_spiregret() As String
            Get
                Return ResourceManager.GetString("fcusb_jtag_spiregret", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to JTAG configuración del motor con éxito.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_jtagsetup() As String
            Get
                Return ResourceManager.GetString("fcusb_jtagsetup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Longitud.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_length() As String
            Get
                Return ResourceManager.GetString("fcusb_length", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Versión LibUsbDotNet: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_libusb_ver() As String
            Get
                Return ResourceManager.GetString("fcusb_libusb_ver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dirección.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_address() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_address", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El usuario ha cancelado la operación de escritura.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_cancelled() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_cancelled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleccione el archivo para escribir en {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_choosefile() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_choosefile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error, el archivo no existe o no contiene datos.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error al intentar leer los datos.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Archivo elegido, escribiendo en {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_filechosen() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_filechosen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Archivo abierto para escritura: {0} (formato binario hexadecimal), el tamaño total del archivo: {1} bytes.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_opened_bin() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_opened_bin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Archivo abierto para escritura: {0} (formato Intel hexadecimal), el tamaño total del archivo: {1} bytes.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_opened_intel() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_opened_intel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La operación de lectura cancelada.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_readcanceled() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_readcanceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lea completa, por favor elija el tipo de ubicación y el formato.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_readcomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_readcomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleccione el rango de lectura de {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_readfrom() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_readfrom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A partir de la memoria la operación de lectura.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_readstart() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_readstart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleccione el rango para escribir datos en {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_selectwriterange() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_selectwriterange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El usuario ha cancelado la operación de lectura.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_usercanceledread() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_usercanceledread", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El usuario ha cancelado. No hay datos escritos en {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_usercanwrite() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_usercanwrite", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash operación de escritura cancelada.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_writecanceled() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_writecanceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Escribir operación completa: {0} bytes por escrito..
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_writecomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_writecomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A partir de la memoria operación de escritura.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_writestart() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_writestart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Escribir el archivo {0} en {1} ({2} bytes a escribir).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_mem_writing() As String
            Get
                Return ResourceManager.GetString("fcusb_mem_writing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Memoria del dispositivo.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memdev() As String
            Get
                Return ResourceManager.GetString("fcusb_memdev", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A partir de la memoria leen de {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_beginread() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_beginread", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Borrado masivo no es compatible con los dispositivos DRAM.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_dram_notsup() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_dram_notsup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MemoryInit: Error - los parámetros del dispositivo no Init.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se puede detectar SPI Flash (API no se ha cargado para la corriente MCU).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MemoryInit: Error - No se puede conectar a la interfaz de memoria de PrAcc (firmware no es compatible con AVR).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_nopraccsupport() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_nopraccsupport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La operación de lectura completo.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_readdone() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_readdone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dirección de inicio: Duración {0} ({1}): {2} &quot;.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_startaddr() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_startaddr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verificando los datos escritos en {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_verify() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_verify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: Flash comprobar leer un número incorrecto de bytes.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_verifyerr1() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_verifyerr1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dirección {0}: {1} escribió y leer {2} ({3} desajustes).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_verifyerr2() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_verifyerr2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: la verificación de datos en {0}!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_verifyfailed() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_verifyfailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verificación de datos se ha realizado correctamente.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_verifyokay() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_verifyokay", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se puede escribir los datos (el dispositivo es de sólo lectura).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_write_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_write_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Escribir la dirección {0} con {1} bytes ({2}).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_writeaddr() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_writeaddr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Escriba el funcionamiento de Flash completo!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_writecomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_writecomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Escribir operación completa, {0} bytes por escrito..
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_writedone() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_writedone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} bytes escritos en el segundo {1}, {2} Bytes/s.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_memif_writespeed() As String
            Get
                Return ResourceManager.GetString("fcusb_memif_writespeed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AVR firmware.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_avrfw() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_avrfw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consola.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_console() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_console", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Script actual.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_cscript() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_cscript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detectar el dispositivo.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_detectdevice() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_detectdevice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Salida.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_exit() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_exit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lengua.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_language() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_language", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cargar secuencia de comandos.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_loadscript() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_loadscript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Principal.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_main() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_main", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Guión.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_script() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_script", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configuración.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_settings() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Utilice la configuración automática.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_auto() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_auto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bit Orden.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_bitorder() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_bitorder", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chip de Borrar.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_chiperase() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_chiperase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chip de Tamaño.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_chipsize() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_chipsize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Divisor de reloj.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_clodiv() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_clodiv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI comandos de dispositivos.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_devcmds() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_devcmds", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Habilitar Escribe Estado.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_enwrstatus() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_enwrstatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Borrar Tamaño.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_erasesize() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_erasesize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Utilice los valores que se encuentran comúnmente en la hoja de datos del dispositivo.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_info() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_info", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modo de programación.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_pmode() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_pmode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Página del Programa.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_pp() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_pp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Leer.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_read() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_read", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Leer estado.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_rstatus() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_rstatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sector Borrar.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_serase() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_serase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modo SPI.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_spimode() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_spimode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Utilice estos ajustes.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_usesettings() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_usesettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Use &apos;Activar Escribe Estado&apos;.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_usewren() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_usewren", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Escribir Habilitar.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_we() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_we", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Escribe Estado.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spi_wstatus() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spi_wstatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configuración de SPI.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_spisettings() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_spisettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estado.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_status() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Descargue secuencia de comandos.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_unloadscript() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_unloadscript", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Verifique la programación.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_menu_verify() As String
            Get
                Return ResourceManager.GetString("fcusb_menu_verify", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El dispositivo conectado en la NAND en modo SPI.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nand_conn() As String
            Get
                Return ResourceManager.GetString("fcusb_nand_conn", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB listo para funcionar en modo NAND.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nand_ready() As String
            Get
                Return ResourceManager.GetString("fcusb_nand_ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nueva programación AVR firmware.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_newavrfw() As String
            Get
                Return ResourceManager.GetString("fcusb_newavrfw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (Sin flash detectado).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_noflash() As String
            Get
                Return ResourceManager.GetString("fcusb_noflash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Los datos leídos satisfactoriamente y se analiza.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_dataread() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_dataread", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error: No se encuentra la zona CFG!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error al cargar los datos para non-vol.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (No se ha encontrado).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_notfound() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_notfound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lectura para Non-Vol datos de configuración.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_readingnonvol() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_readingnonvol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Escribir para no vol configuración para Flash.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_writing() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_writing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hecho. Non-Vol. configuración actualizada.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_nonvol_wrote() As String
            Get
                Return ResourceManager.GetString("fcusb_nonvol_wrote", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aceptar.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_okbutton() As String
            Get
                Return ResourceManager.GetString("fcusb_okbutton", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rango:.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_range() As String
            Get
                Return ResourceManager.GetString("fcusb_range", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Leer.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_Read() As String
            Get
                Return ResourceManager.GetString("fcusb_Read", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Correr en: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_running() As String
            Get
                Return ResourceManager.GetString("fcusb_running", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comprobación de un guión de un dispositivo específico para cargar automáticamente.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_check() As String
            Get
                Return ResourceManager.GetString("fcusb_script_check", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Script cargado {0} con éxito.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_loaded() As String
            Get
                Return ResourceManager.GetString("fcusb_script_loaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Carga de secuencia de comandos de un dispositivo específico: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_loading() As String
            Get
                Return ResourceManager.GetString("fcusb_script_loading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No hay archivos de comandos disponibles.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_none() As String
            Get
                Return ResourceManager.GetString("fcusb_script_none", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se puede cargar script (archivo no existe).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_notexist() As String
            Get
                Return ResourceManager.GetString("fcusb_script_notexist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seleccione el archivo FlashcatUSB secuencia de comandos para abrir.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_open() As String
            Get
                Return ResourceManager.GetString("fcusb_script_open", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El guión {0} se ha descargado.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_script_unload() As String
            Get
                Return ResourceManager.GetString("fcusb_script_unload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Conectado a Flash.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_connflash() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_connflash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Para lectura y escritura contact@embeddedcomputers.net soporte por correo electrónico con JEDEC ID.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_email() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flash Erase completar en {0} segundos.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_erasecomplete() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_erasecomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Borrado de todo el dispositivo de memoria flash, el tamaño total: {0} bytes (esto puede tardar un momento).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_erasingbulk() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_erasingbulk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB conectado en modo SPI, pero no detectaron flash.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_err1() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_err1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB detectado dispositivo SPI pero no es compatible en la actualidad.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_err2() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_err2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tamaño del SPI dispositivo debe ser al menos un megabit.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_err3() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_err3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tamaño del SPI dispositivo debe ser un múltiplo de un megabit.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_err4() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_err4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No se puede conectar al dispositivo compatible con SPI.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_err5() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_err5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Detectado Flash para: {0} ({1} bytes).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_flashdetected() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_flashdetected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error de configuración de SPI, el modo no es compatible: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_modenotsupported() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_modenotsupported", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI de modo ajustado en auto configurar.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_modesetauto() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_modesetauto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SPI de modo ajustado en {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_modesetto() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_modesetto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La apertura del dispositivo en modo SPI.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_openinmode() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_openinmode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modo de programación: SPI (alta velocidad).
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_progmode() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_progmode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FlashcatUSB listo para funcionar en modo SPI.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_ready() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_ready", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La búsqueda de los SPI Flash.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_scanning() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_scanning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Utilización de los ajustes personalizados de la página Configuración de SPI.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_usingcustom() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_usingcustom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El dispositivo conectado en modo SPI, la versión del firmware: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_spi_ver() As String
            Get
                Return ResourceManager.GetString("fcusb_spi_ver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estado de FlashcatUSB: Conectado.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_status_connected() As String
            Get
                Return ResourceManager.GetString("fcusb_status_connected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Estado de FlashcatUSB: Desconectado.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_status_disconnect() As String
            Get
                Return ResourceManager.GetString("fcusb_status_disconnect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to STOP.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_stop() As String
            Get
                Return ResourceManager.GetString("fcusb_stop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Software de espera para el dispositivo que se conecta a través de USB.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_waitingforusb() As String
            Get
                Return ResourceManager.GetString("fcusb_waitingforusb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bienvenido al software de interfaz FlashcatUSB, construir: {0}.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_welcome() As String
            Get
                Return ResourceManager.GetString("fcusb_welcome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bienvenido a FlashcatUSB!.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_welcome_status() As String
            Get
                Return ResourceManager.GetString("fcusb_welcome_status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Escribir.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_Write() As String
            Get
                Return ResourceManager.GetString("fcusb_Write", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Acelerar.
        '''</summary>
        Friend Shared ReadOnly Property fcusb_xferspeed() As String
            Get
                Return ResourceManager.GetString("fcusb_xferspeed", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
